# Generated by Django 4.2.9 on 2025-11-14 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً: صورتحساب آبان ۱۴۰۴",
                        max_length=255,
                        verbose_name="عنوان صورتحساب",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to="invoices/%Y/%m/", verbose_name="فایل اکسل صورتحساب"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="تعداد ردیف\u200cها (بعداً محاسبه می\u200cشود)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "آپلود شده"),
                            ("processing", "در حال پردازش"),
                            ("done", "پردازش شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, verbose_name="پیغام خطا (در صورت وجود)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل صورتحساب",
                "verbose_name_plural": "فایل\u200cهای صورتحساب",
                "ordering": ("-uploaded_at",),
            },
        ),
    ]
