# Generated by Django 4.2.9 on 2025-11-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("digihesabyar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicefile",
            name="row_count",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="تعداد ردیف\u200cها (بعداً از روی InvoiceRow پر می\u200cشود)",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("cash", "فروش نقدی"), ("credit", "فروش اعتباری")],
                        max_length=10,
                        verbose_name="نوع فروش",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(max_length=64, verbose_name="شماره سفارش"),
                ),
                (
                    "dkpc",
                    models.CharField(max_length=64, verbose_name="کد تنوع (DKPC)"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان تنوع")),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ فروش"),
                ),
                (
                    "sale_amount",
                    models.BigIntegerField(default=0, verbose_name="مبلغ فروش (ریال)"),
                ),
                (
                    "is_return",
                    models.BooleanField(default=False, verbose_name="آیا مرجوعی است؟"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="digihesabyar.invoicefile",
                        verbose_name="فایل صورتحساب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیف فروش",
                "verbose_name_plural": "ردیف\u200cهای فروش",
                "indexes": [
                    models.Index(
                        fields=["invoice", "sale_type"],
                        name="digihesabya_invoice_a17dbe_idx",
                    ),
                    models.Index(
                        fields=["invoice", "order_id", "dkpc"],
                        name="digihesabya_invoice_1906d4_idx",
                    ),
                ],
            },
        ),
    ]
