# Generated by Django 4.2.9 on 2025-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digihesabyar", "0002_alter_invoicefile_row_count_invoicerow"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerow",
            name="commission_amount",
            field=models.BigIntegerField(default=0, verbose_name="کمیسیون فروش (ریال)"),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="platform_dev_revenue",
            field=models.BigIntegerField(
                default=0, verbose_name="درآمد توسعه پلتفرم (ریال)"
            ),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="processing_fee",
            field=models.BigIntegerField(default=0, verbose_name="هزینه پردازش (ریال)"),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="shipping_fee",
            field=models.BigIntegerField(default=0, verbose_name="هزینه ارسال (ریال)"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="order_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="شماره سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="عنوان تنوع"
            ),
        ),
    ]
