# Generated by Django 4.2.9 on 2025-11-15 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("digihesabyar", "0003_invoicerow_commission_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerow",
            name="profit",
            field=models.BigIntegerField(default=0, verbose_name="سود این ردیف (ریال)"),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="purchase_price",
            field=models.BigIntegerField(
                default=0, verbose_name="قیمت خرید (ریال) برای هر واحد"
            ),
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dkpc",
                    models.CharField(max_length=64, verbose_name="کد تنوع (DKPC)"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان تنوع"
                    ),
                ),
                (
                    "purchase_price",
                    models.BigIntegerField(default=0, verbose_name="قیمت خرید (ریال)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "قیمت خرید کالا",
                "verbose_name_plural": "قیمت\u200cهای خرید کالاها",
                "unique_together": {("user", "dkpc")},
            },
        ),
    ]
