# Generated by Django 4.2.9 on 2025-11-16 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("digihesabyar", "0004_invoicerow_profit_invoicerow_purchase_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام طرح")),
                (
                    "min_rows",
                    models.PositiveIntegerField(verbose_name="حداقل تعداد ردیف"),
                ),
                (
                    "max_rows",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="حداکثر تعداد ردیف (خالی = نامحدود)",
                    ),
                ),
                (
                    "price_per_invoice",
                    models.PositiveBigIntegerField(
                        verbose_name="هزینه پردازش هر صورتحساب (ریال)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
            ],
            options={
                "verbose_name": "طرح قیمت\u200cگذاری",
                "verbose_name_plural": "طرح\u200cهای قیمت\u200cگذاری",
                "ordering": ("min_rows",),
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.BigIntegerField(default=0, verbose_name="موجودی (ریال)"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف\u200cهای پول",
            },
        ),
        migrations.AddField(
            model_name="invoicefile",
            name="is_paid",
            field=models.BooleanField(
                default=False, verbose_name="آیا صورتحساب پرداخت شده است؟"
            ),
        ),
        migrations.AddField(
            model_name="invoicefile",
            name="price_amount",
            field=models.BigIntegerField(
                default=0, verbose_name="هزینه پردازش این صورتحساب (ریال)"
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ تراکنش"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("charge", "شارژ کیف پول"),
                            ("invoice", "پرداخت صورتحساب"),
                            ("refund", "بازگشت وجه"),
                            ("adjust", "اصلاح دستی"),
                        ],
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        verbose_name="مبلغ (ریال؛ مثبت=واریز، منفی=برداشت)"
                    ),
                ),
                (
                    "balance_after",
                    models.BigIntegerField(verbose_name="موجودی بعد از تراکنش (ریال)"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="digihesabyar.invoicefile",
                        verbose_name="صورتحساب مرتبط",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="digihesabyar.wallet",
                        verbose_name="کیف پول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش کیف پول",
                "verbose_name_plural": "تراکنش\u200cهای کیف پول",
                "ordering": ("-created_at",),
            },
        ),
    ]
