# Generated by Django 4.2.9 on 2025-11-16 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("digihesabyar", "0005_pricingtier_wallet_invoicefile_is_paid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicefile",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "فایل صورتحساب",
                "verbose_name_plural": "فایل\u200cهای صورتحساب",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicerow",
            options={
                "ordering": ["invoice", "sale_type", "order_id", "dkpc"],
                "verbose_name": "ردیف صورتحساب",
                "verbose_name_plural": "ردیف\u200cهای صورتحساب",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingtier",
            options={
                "ordering": ["min_rows"],
                "verbose_name": "تعرفه صورتحساب",
                "verbose_name_plural": "تعرفه\u200cهای صورتحساب",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "verbose_name": "کیف\u200cپول",
                "verbose_name_plural": "کیف\u200cپول کاربران",
            },
        ),
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تراکنش کیف\u200cپول",
                "verbose_name_plural": "تراکنش\u200cهای کیف\u200cپول",
            },
        ),
        migrations.RemoveIndex(
            model_name="invoicerow",
            name="digihesabya_invoice_a17dbe_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoicerow",
            name="digihesabya_invoice_1906d4_idx",
        ),
        migrations.RenameField(
            model_name="wallettransaction",
            old_name="reason",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="invoicefile",
            name="price_amount",
        ),
        migrations.RemoveField(
            model_name="invoicerow",
            name="date",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="balance_after",
        ),
        migrations.AddField(
            model_name="invoicefile",
            name="processing_price",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="هزینه پردازش این صورتحساب (ریال)"
            ),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="tax_amount",
            field=models.BigIntegerField(default=0, verbose_name="مالیات خدمات (ریال)"),
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="is_paid",
            field=models.BooleanField(
                default=False, verbose_name="صورتحساب پرداخت شده است؟"
            ),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="original_file",
            field=models.FileField(
                upload_to="invoices/", verbose_name="فایل اکسل صورتحساب"
            ),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="row_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="تعداد ردیف\u200cهای فروش"
            ),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در صف پردازش"),
                    ("processing", "در حال پردازش"),
                    ("done", "پردازش\u200cشده"),
                    ("error", "خطا در پردازش"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت پردازش",
            ),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="عنوان صورتحساب"
            ),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="commission_amount",
            field=models.BigIntegerField(default=0, verbose_name="کمیسیون (ریال)"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="dkpc",
            field=models.CharField(max_length=100, verbose_name="کد تنوع (DKPC)"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="digihesabyar.invoicefile",
                verbose_name="صورتحساب",
            ),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="is_return",
            field=models.BooleanField(default=False, verbose_name="مرجوعی است؟"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="order_id",
            field=models.CharField(max_length=100, verbose_name="شماره سفارش"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="profit",
            field=models.BigIntegerField(default=0, verbose_name="سود / زیان (ریال)"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="purchase_price",
            field=models.BigIntegerField(default=0, verbose_name="قیمت خرید (ریال)"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="sale_amount",
            field=models.BigIntegerField(default=0, verbose_name="قیمت فروش (ریال)"),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="sale_type",
            field=models.CharField(
                choices=[("cash", "نقدی"), ("credit", "اعتباری")],
                max_length=10,
                verbose_name="نوع فروش",
            ),
        ),
        migrations.AlterField(
            model_name="invoicerow",
            name="title",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="عنوان تنوع"
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="max_rows",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="حداکثر تعداد ردیف (خالی = بدون سقف)",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام تعرفه"),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price_per_invoice",
            field=models.PositiveBigIntegerField(
                verbose_name="هزینه این صورتحساب (ریال)"
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="dkpc",
            field=models.CharField(max_length=100, verbose_name="کد تنوع (DKPC)"),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="title",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="عنوان تنوع"
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.BigIntegerField(verbose_name="مبلغ (ریال)"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("charge", "شارژ کیف\u200cپول"),
                    ("invoice", "پرداخت صورتحساب"),
                    ("refund", "بازگشت وجه"),
                    ("adjust", "اصلاح دستی"),
                ],
                max_length=20,
                verbose_name="نوع تراکنش",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="digihesabyar.wallet",
                verbose_name="کیف\u200cپول",
            ),
        ),
    ]
