# Generated by Django 4.2.9 on 2025-11-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digihesabyar",
            "0006_alter_invoicefile_options_alter_invoicerow_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicefile",
            name="coupon_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="کد تخفیف استفاده\u200cشده"
            ),
        ),
        migrations.AddField(
            model_name="invoicefile",
            name="paid_amount",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="مبلغ پرداخت\u200cشده (ریال)"
            ),
        ),
    ]
