# Generated by Django 4.2.9 on 2025-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digihesabyar", "0007_invoicefile_coupon_code_invoicefile_paid_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد کوپن"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(
                        help_text="عدد بین ۱ تا ۱۰۰ (مثلاً ۲۰ یعنی ۲۰٪ تخفیف).",
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اگر خالی باشد، استفاده نامحدود است.",
                        null=True,
                        verbose_name="حداکثر دفعات استفاده",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده شده"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ شروع اعتبار"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پایان اعتبار"
                    ),
                ),
            ],
            options={
                "verbose_name": "کوپن تخفیف",
                "verbose_name_plural": "کوپن\u200cها",
            },
        ),
    ]
