# Generated by Django 4.2.9 on 2025-11-18 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("digihesabyar", "0008_coupon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "verbose_name": "کیف پول",
                "verbose_name_plural": "کیف پول\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تراکنش کیف پول",
                "verbose_name_plural": "تراکنش\u200cهای کیف پول",
            },
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="invoicefile",
            name="coupon_code",
        ),
        migrations.RemoveField(
            model_name="invoicefile",
            name="paid_amount",
        ),
        migrations.AddField(
            model_name="coupon",
            name="percent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="درصد تخفیف (۰ تا ۱۰۰)"
            ),
        ),
        migrations.AddField(
            model_name="invoicefile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد رکورد",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="حداکثر دفعات استفاده (خالی = بدون محدودیت)",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="معتبر از تاریخ"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="معتبر تا تاریخ"
            ),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="متن خطا (در صورت وجود)"),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="پرداخت شده است؟"),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="row_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="تعداد ردیف\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="invoicefile",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="digihesabyar.invoicefile",
                verbose_name="صورتحساب مربوطه (در صورت وجود)",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[("credit", "واریز"), ("debit", "برداشت")],
                max_length=10,
                verbose_name="نوع تراکنش",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="digihesabyar.wallet",
                verbose_name="کیف پول",
            ),
        ),
    ]
